# Generated by Django 4.1.7 on 2023-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="total_marks",
        ),
        migrations.AddField(
            model_name="test",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="questions",
            field=models.ManyToManyField(related_name="tests", to="main.question"),
        ),
    ]
