# Generated by Django 4.1.7 on 2023-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_test_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="attempted_option",
            field=models.CharField(default="Not Attempted", max_length=5000, null=True),
        ),
    ]
