# Generated by Django 4.2.1 on 2023-05-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_testquestion_attempted_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="marks_obtained",
            field=models.FloatField(default=0),
        ),
    ]
